2025-02-24 17:58:13.09
36a2af4c
User
Invalid session f3ErojziPIjcL3dYAAAE (further occurrences of this error will be logged with level INFO)
2025-02-24 17:58:13.09
36a2af4c
User
ERROR:engineio.server:Invalid session f3ErojziPIjcL3dYAAAE (further occurrences of this error will be logged with level INFO)
2025-02-24 17:58:13.09
36a2af4c
User
Invalid session f3ErojziPIjcL3dYAAAE
2025-02-24 17:58:13.09
36a2af4c
User
INFO:engineio.server:Invalid session f3ErojziPIjcL3dYAAAE
2025-02-24 17:58:13.09
47f32766
User
[2025-02-24 15:58:13 +0000] [24] [INFO] Shutting down: Master
2025-02-24 17:58:13.11
47f32766
System
command finished successfully with exit code 0
2025-02-24 17:58:13.11
47f32766
System
main done, exiting
2025-02-24 17:58:13.28
36a2af4c
User
Invalid session f3ErojziPIjcL3dYAAAE
2025-02-24 17:58:13.28
36a2af4c
User
INFO:engineio.server:Invalid session f3ErojziPIjcL3dYAAAE
2025-02-24 17:58:14.09
36a2af4c
User
Rz40B0ri16R7ZAEJAAAA: Sending packet OPEN data {'sid': 'Rz40B0ri16R7ZAEJAAAA', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000, 'maxPayload': 1000000}
2025-02-24 17:58:14.09
36a2af4c
User
INFO:engineio.server:Rz40B0ri16R7ZAEJAAAA: Sending packet OPEN data {'sid': 'Rz40B0ri16R7ZAEJAAAA', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000, 'maxPayload': 1000000}
2025-02-24 17:58:39.11
36a2af4c
User
Rz40B0ri16R7ZAEJAAAA: Sending packet PING data None
2025-02-24 17:58:39.11
36a2af4c
User
INFO:engineio.server:Rz40B0ri16R7ZAEJAAAA: Sending packet PING data None
2025-02-24 17:58:39.12
36a2af4c
User
Rz40B0ri16R7ZAEJAAAA: Received packet MESSAGE data 0
2025-02-24 17:58:39.12
36a2af4c
User
INFO:engineio.server:Rz40B0ri16R7ZAEJAAAA: Received packet MESSAGE data 0
2025-02-24 17:58:39.12
36a2af4c
User
INFO:root:Client connected
2025-02-24 17:58:39.12
36a2af4c
User
Rz40B0ri16R7ZAEJAAAA: Sending packet MESSAGE data 0{"sid":"JvUcTuu7f6RHXmLRAAAB"}
2025-02-24 17:58:39.12
36a2af4c
User
INFO:engineio.server:Rz40B0ri16R7ZAEJAAAA: Sending packet MESSAGE data 0{"sid":"JvUcTuu7f6RHXmLRAAAB"}
2025-02-24 17:58:39.12
36a2af4c
User
Rz40B0ri16R7ZAEJAAAA: Received request to upgrade to websocket
2025-02-24 17:58:39.12
36a2af4c
User
INFO:engineio.server:Rz40B0ri16R7ZAEJAAAA: Received request to upgrade to websocket
2025-02-24 17:58:39.14
36a2af4c
User
[2025-02-24 15:58:39 +0000] [30] [ERROR] Error handling request /socket.io/?EIO=4&transport=websocket&sid=Rz40B0ri16R7ZAEJAAAA
2025-02-24 17:58:39.14
36a2af4c
User
Traceback (most recent call last):
2025-02-24 17:58:39.14
36a2af4c
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 134, in handle
2025-02-24 17:58:39.14
36a2af4c
User
self.handle_request(listener, req, client, addr)
2025-02-24 17:58:39.14
36a2af4c
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
2025-02-24 17:58:39.14
36a2af4c
User
respiter = self.wsgi(environ, resp.start_response)
2025-02-24 17:58:39.14
36a2af4c
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-24 17:58:39.14
36a2af4c
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
2025-02-24 17:58:39.14
36a2af4c
User
return self.wsgi_app(environ, start_response)
2025-02-24 17:58:39.14
36a2af4c
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-24 17:58:39.14
36a2af4c
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask_socketio/__init__.py", line 42, in __call__
2025-02-24 17:58:39.14
36a2af4c
User
return super().__call__(environ, start_response)
2025-02-24 17:58:39.14
36a2af4c
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-24 17:58:39.14
36a2af4c
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/engineio/middleware.py", line 63, in __call__
2025-02-24 17:58:39.14
36a2af4c
User
return self.engineio_app.handle_request(environ, start_response)
2025-02-24 17:58:39.14
36a2af4c
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-24 17:58:39.14
36a2af4c
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/socketio/server.py", line 434, in handle_request
2025-02-24 17:58:39.14
36a2af4c
User
return self.eio.handle_request(environ, start_response)
2025-02-24 17:58:39.14
36a2af4c
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-24 17:58:39.14
36a2af4c
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/engineio/server.py", line 286, in handle_request
2025-02-24 17:58:39.14
36a2af4c
User
packets = socket.handle_get_request(
2025-02-24 17:58:39.14
36a2af4c
User
^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-24 17:58:39.14
36a2af4c
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/engineio/socket.py", line 92, in handle_get_request
2025-02-24 17:58:39.14
36a2af4c
User
return getattr(self, '_upgrade_' + transport)(environ,
2025-02-24 17:58:39.14
36a2af4c
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-24 17:58:39.14
36a2af4c
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/engineio/socket.py", line 151, in _upgrade_websocket
2025-02-24 17:58:39.14
36a2af4c
User
return ws(environ, start_response)
2025-02-24 17:58:39.14
36a2af4c
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-24 17:58:39.14
36a2af4c
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/engineio/async_drivers/gevent.py", line 54, in __call__
2025-02-24 17:58:39.14
36a2af4c
User
raise RuntimeError('The gevent-websocket server is not '
2025-02-24 17:58:39.14
36a2af4c
User
RuntimeError: The gevent-websocket server is not configured appropriately. See the Deployment section of the documentation for more information.
2025-02-24 17:58:39.14
36a2af4c
User
Rz40B0ri16R7ZAEJAAAA: Received packet CLOSE data