2025-02-24 16:59:04.68
dbb4ba2a
User
[2025-02-24 14:59:04 +0000] [31] [ERROR] Error handling request /socket.io/?EIO=4&transport=websocket&sid=HrqwnCtEHrfn7wCeAAAA
2025-02-24 16:59:04.68
dbb4ba2a
User
Traceback (most recent call last):
2025-02-24 16:59:04.68
dbb4ba2a
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 134, in handle
2025-02-24 16:59:04.68
dbb4ba2a
User
self.handle_request(listener, req, client, addr)
2025-02-24 16:59:04.68
dbb4ba2a
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
2025-02-24 16:59:04.68
dbb4ba2a
User
respiter = self.wsgi(environ, resp.start_response)
2025-02-24 16:59:04.68
dbb4ba2a
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-24 16:59:04.68
dbb4ba2a
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
2025-02-24 16:59:04.68
dbb4ba2a
User
return self.wsgi_app(environ, start_response)
2025-02-24 16:59:04.68
dbb4ba2a
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-24 16:59:04.68
dbb4ba2a
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask_socketio/__init__.py", line 42, in __call__
2025-02-24 16:59:04.68
dbb4ba2a
User
return super().__call__(environ, start_response)
2025-02-24 16:59:04.68
dbb4ba2a
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-24 16:59:04.68
dbb4ba2a
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/engineio/middleware.py", line 63, in __call__
2025-02-24 16:59:04.68
dbb4ba2a
User
return self.engineio_app.handle_request(environ, start_response)
2025-02-24 16:59:04.68
dbb4ba2a
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-24 16:59:04.68
dbb4ba2a
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/socketio/server.py", line 434, in handle_request
2025-02-24 16:59:04.68
dbb4ba2a
User
return self.eio.handle_request(environ, start_response)
2025-02-24 16:59:04.68
dbb4ba2a
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-24 16:59:04.68
dbb4ba2a
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/engineio/server.py", line 286, in handle_request
2025-02-24 16:59:04.68
dbb4ba2a
User
packets = socket.handle_get_request(
2025-02-24 16:59:04.68
dbb4ba2a
User
^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-24 16:59:04.68
dbb4ba2a
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/engineio/socket.py", line 92, in handle_get_request
2025-02-24 16:59:04.68
dbb4ba2a
User
return getattr(self, '_upgrade_' + transport)(environ,
2025-02-24 16:59:04.68
dbb4ba2a
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-24 16:59:04.68
dbb4ba2a
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/engineio/socket.py", line 151, in _upgrade_websocket
2025-02-24 16:59:04.68
dbb4ba2a
User
return ws(environ, start_response)
2025-02-24 16:59:04.68
dbb4ba2a
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-24 16:59:04.68
dbb4ba2a
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/engineio/async_drivers/gevent.py", line 54, in __call__
2025-02-24 16:59:04.68
dbb4ba2a
User
raise RuntimeError('The gevent-websocket server is not '
2025-02-24 16:59:04.68
dbb4ba2a
User
RuntimeError: The gevent-websocket server is not configured appropriately. See the Deployment section of the documentation for more information.
2025-02-24 16:59:29.35
dbb4ba2a
User
HrqwnCtEHrfn7wCeAAAA: Sending packet PING data None
2025-02-24 16:59:29.35
dbb4ba2a
User
INFO:engineio.server:HrqwnCtEHrfn7wCeAAAA: Sending packet PING data None
2025-02-24 16:59:29.35
dbb4ba2a
User
HrqwnCtEHrfn7wCeAAAA: Received packet CLOSE data
2025-02-24 16:59:29.35
dbb4ba2a
User
INFO:engineio.server:HrqwnCtEHrfn7wCeAAAA: Received packet CLOSE data
2025-02-24 16:59:29.35
dbb4ba2a
User
ERROR:root:SocketIO Error: handle_disconnect() takes 0 positional arguments but 1 was given
2025-02-24 17:00:24.82
58131014
System
starting up user application
2025-02-24 17:00:25.06
58131014
System
forwarding local port 5000 to external port 80
2025-02-24 17:04:35.42
dbb4ba2a
System
system: received signal terminated
2025-02-24 17:04:35.42
dbb4ba2a
User
[2025-02-24 15:04:35 +0000] [26] [INFO] Handling signal: term
2025-02-24 17:04:35.42
dbb4ba2a
User
[2025-02-24 15:04:35 +0000] [31] [INFO] Worker exiting (pid: 31)
2025-02-24 17:04:35.82
dbb4ba2a
User
[2025-02-24 15:04:35 +0000] [26] [INFO] Shutting down: Master
2025-02-24 17:04:35.86
dbb4ba2a
System
command finished successfully with exit code 0
2025-02-24 17:04:35.86
dbb4ba2a
System
main done, exiting
2025-02-24 17:06:43.01
58131014
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask_socketio/__init__.py", line 42, in __call__
2025-02-24 17:06:43.01
58131014
User
return super().__call__(environ, start_response)
2025-02-24 17:06:43.01
58131014
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-24 17:06:43.01
58131014
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/engineio/middleware.py", line 63, in __call__
2025-02-24 17:06:43.01
58131014
User
return self.engineio_app.handle_request(environ, start_response)