2025-02-19 15:45:07.67
efefa04c
User
[2025-02-19 13:45:07 +0000] [32] [ERROR] Error handling request /socket.io/?EIO=4&transport=websocket&sid=VuCBpk3UA-0c8BbnAAAC
2025-02-19 15:45:07.67
efefa04c
User
Traceback (most recent call last):
2025-02-19 15:45:07.67
efefa04c
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 134, in handle
2025-02-19 15:45:07.67
efefa04c
User
self.handle_request(listener, req, client, addr)
2025-02-19 15:45:07.67
efefa04c
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
2025-02-19 15:45:07.67
efefa04c
User
respiter = self.wsgi(environ, resp.start_response)
2025-02-19 15:45:07.67
efefa04c
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-19 15:45:07.67
efefa04c
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
2025-02-19 15:45:07.67
efefa04c
User
return self.wsgi_app(environ, start_response)
2025-02-19 15:45:07.67
efefa04c
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-19 15:45:07.67
efefa04c
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask_socketio/__init__.py", line 42, in __call__
2025-02-19 15:45:07.67
efefa04c
User
return super().__call__(environ, start_response)
2025-02-19 15:45:07.67
efefa04c
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-19 15:45:07.67
efefa04c
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/engineio/middleware.py", line 63, in __call__
2025-02-19 15:45:07.67
efefa04c
User
return self.engineio_app.handle_request(environ, start_response)
2025-02-19 15:45:07.67
efefa04c
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-19 15:45:07.67
efefa04c
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/socketio/server.py", line 434, in handle_request
2025-02-19 15:45:07.67
efefa04c
User
return self.eio.handle_request(environ, start_response)
2025-02-19 15:45:07.67
efefa04c
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-19 15:45:07.67
efefa04c
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/engineio/server.py", line 286, in handle_request
2025-02-19 15:45:07.67
efefa04c
User
packets = socket.handle_get_request(
2025-02-19 15:45:07.67
efefa04c
User
^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-19 15:45:07.67
efefa04c
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/engineio/socket.py", line 92, in handle_get_request
2025-02-19 15:45:07.67
efefa04c
User
return getattr(self, '_upgrade_' + transport)(environ,
2025-02-19 15:45:07.67
efefa04c
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-19 15:45:07.67
efefa04c
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/engineio/socket.py", line 151, in _upgrade_websocket
2025-02-19 15:45:07.67
efefa04c
User
return ws(environ, start_response)
2025-02-19 15:45:07.67
efefa04c
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-19 15:45:07.67
efefa04c
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/engineio/async_drivers/gevent.py", line 54, in __call__
2025-02-19 15:45:07.67
efefa04c
User
raise RuntimeError('The gevent-websocket server is not '
2025-02-19 15:45:07.67
efefa04c
User
RuntimeError: The gevent-websocket server is not configured appropriately.